version: "3.7"



services:

  fastapi-app:

    build:

      context: ./fastapi-app

      dockerfile: Dockerfile

    container_name: FastApi-app

    ports:

      - "5001:5001"



  sonarqube:

    image: sonarqube:latest

    container_name: sonarqube

    ports:

      - "9000:9000"

    environment:

      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true

    volumes:

      - sonarqube_conf:/opt/sonarqube/conf

      - sonarqube_data:/opt/sonarqube/data

      - sonarqube_logs:/opt/sonarqube/logs

      - sonarqube_extensions:/opt/sonarqube/extensions



volumes:

  sonarqube_conf:

  sonarqube_data:

  sonarqube_logs:

  sonarqube_extensions:
